name: roulette-game
on:
  push:
    branches: [main]
jobs:
  fighting-game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Build my App
        run: npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          GITHUB_TOKEN: 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
          BRANCH: gh-pages
          FOLDER: dist
